### PR TITLE
Add an action to copy the s3 uri and group them into an action group

### PR DESCRIPTION
**Pull request by hunterwerlla**
## Screenshots
Screen Shot 2020-12-07 at 9 51 13 AM

## Related issues 
#2208
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by abrooksv** [comment]
Does this remove Copy URL from the toolboar? (It should be probably given lack of an icon)

**Comment by hunterwerlla** [comment]
> Does this remove Copy URL from the toolboar? (It should be probably given lack of an icon)

I forgot about that, it's actually very wonky, will fix

**Comment by kiiadi** [comment]
can you also do this to the copy actions in the footer?  
Screen Shot 2020-12-07 at 10 56 56 AM

**Review by abrooksv — APPROVED** [review]

**Comment by hunterwerlla** [comment]
> can you also do this to the copy actions in the footer?
> Screen Shot 2020-12-07 at 10 56 56 AM

That doesn't actually work unless we want to unwrap from the action group. Having 3 copy actions there would be confusing, so I removed it entirely.

**Pull request merged**
