### PR TITLE
Batched Lambda changes

### PR DESCRIPTION
**Pull request by rli**
```
+ Python 3.12, Java 21, Node.js 20
- .NET 5.0, Java 8 (AL2012), Python 3.7, Node.js 14
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] My code follows the code style of this project
- [ ] I have added tests to cover my changes
- [ ] A short description of the change has been added to the **[CHANGELOG](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md#contributing-via-pull-requests)** if the change is customer-facing in the IDE.
- [ ] I have added metrics for my changes (if required)
 
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by manodnyab — APPROVED** [review]
Can you please add a changelog?

**Comment by rli** [comment]
```
    Traceback (most recent call last):
      File "/tmp/lambci_debug_files/pydevd.py", line 44, in <module>
        import pydevd_tracing
      File "/tmp/lambci_debug_files/pydevd_tracing.py", line 1, in <module>
        import ctypes
      File "/var/lang/lib/python3.11/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    05 Dec 2023 18:55:33,430 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 1 InvokeID=
    Traceback (most recent call last):
      File "/tmp/lambci_debug_files/pydevd.py", line 44, in <module>
        import pydevd_tracing
      File "/tmp/lambci_debug_files/pydevd_tracing.py", line 1, in <module>
        import ctypes
      File "/var/lang/lib/python3.11/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
```

**Comment by roamingthings** [comment]
My team cannot wait for this to become available. It's currently hard for us to develop/debug Lambda functions in Java 21 locally since we always relied on the AWS Toolkit plugin.

**Comment by dacianf** [comment]
Hey @rli 

Great job with this PR. @manodnyab @rli What is the current status with this PR? Do you know when it's suppose to roll out? Can us the community help in any way?

**Comment by thai-op** [comment]
I'm wondering how long would it take to roll out this new update? I've been maintaining a custom built version for my IDE to work, and Intellij kept replacing it with updated version which doesn't have it. It's super annoying and frustrating since we are using java 21 runtime.

**Comment by thai-op** [comment]
@manodnyab could you help review this PR and push it through? Thank you!

**Comment by j-fraga** [comment]
It would be great if someone could fix the issues with this PR.
Python 3.12 is available on AWS since December, the **aws-toolkit-vscode** already supports it, but still no support is available for jetbrains.

**Pull request merged**
