### PR TITLE
refactor(amazonq): move projectContext folder to amazonq/shared

### PR DESCRIPTION
**Pull request by Will-ShaoHua**
## Description

preparation work for #4976
depends on #4970, #4971
 
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Will-ShaoHua** [comment]
depend on #4970 #4971

**Review by leigaol — COMMENTED** [review]
Please fix these conflicts!

**Review by leigaol — APPROVED** [review]

**Review by manodnyab — APPROVED** [review]

**Pull request merged**
