### PR TITLE
Add option to --use-container during serverless app deployment

### LINKED ISSUE #749: Should the sam build during deploy include "--use-container"?
Or at least an option to include it?

https://github.com/aws/aws-toolkit-jetbrains/blob/0a1728df100f2e2cffd3b47d9289e88768102a0c/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/deploy/SamDeployDialog.kt#L94

I'm running my lambda function in a virtual environment, and it has 2 dependencies, `praw` and `pycrypto`.  My machine python install is under anaconda.  That install has `pycrypto` installed, but not praw.

When I run the default deploy (right-click, `Deploy Serverless Application`), and it runs the `sam build --template .../template.yaml --build-dir .../.aws-sam/build` command, I get an error telling me my module can't be imported because `pycrypto` can't be imported.

When I check the build folder, I see that `praw` has been installed by the pip build process, but `pycrypto` hasn't (because it's already installed on that system python install).

I've actually gone and manually added `--use-container` in to the `sam` script,

    import re
    import sys

    from samcli.cli.main import cli

    if __name__ == '__main__':
        if ('build' in sys.argv) and ('--use-container' not in sys.argv):
            sys.argv.append('--use-container')

        sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
        sys.exit(cli())

And now everything works correctly.

So yeah, should `--use-container` be there by default?  Or at least give us an option to include it?  Because it doesn't seem like the built will build correctly without it.

### PR DESCRIPTION
**Pull request by rli**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Related Issue(s)
Resolves #749 

## Testing
* Visually confirmed that checking the box results in --use-container appended to the build command-line 

## Screenshots (if appropriate)
image

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `gradlew check` succeeds
- [x] My code follows the code style of this project
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jjbuck** [comment]
How do you specify the path of the requirements.txt file? Is it assumed to be in a particular location?

**Comment by abrooksv** [comment]
Sam build expects it to be rooted where your lambda is rooted. See: https://github.com/awslabs/aws-sam-cli/tree/develop/samcli/local/init/templates/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D

**Comment by jjbuck** [comment]
> Sam build expects it to be rooted where your lambda is rooted. See: https://github.com/awslabs/aws-sam-cli/tree/develop/samcli/local/init/templates/cookiecutter-aws-sam-hello-python/%7B%7Bcookiecutter.project_name%7D%7D

Thanks for your prompt reply. I think I flipped back to a different window and figured that out right as you responded and deleted my initial question. For posterity's sake, this did exactly what I wanted.

**Comment by JakeBrainJolt** [comment]
Does anyone know when this will be available in the plugin? I see that it has been merged with the master, and I believe it would fix some resolve dependency issues I'm having.

**Comment by awschristou** [comment]
Hi @JakeBrainJolt this was released in version 1.2 (see [Changelog](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CHANGELOG.md)), please check the version of your toolkit.

**Comment by JakeBrainJolt** [comment]
> 
> 
> Hi @JakeBrainJolt this was released in version 1.2 (see [Changelog](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CHANGELOG.md)), please check the version of your toolkit.

Ah! I see - I am running 1.7 - but I'm pushing my code to lambda from a different place in the toolkit. Are there plans to make this option available when creating a new lambda function from aws toolkit in a "Pure Python" project? I believe this option is only available if the project is created as an "AWS Serverless Application".

**Comment by abrooksv** [comment]
That is not currently supported, and is a known gap

**Pull request merged**
