### PR TITLE
Remove mock region usage from CreateFunctionIntegrationTest

### PR DESCRIPTION
**Pull request by abrooksv**
Since we use the real one (MockClientManager.useRealImplementations), we should not use the mock region rule. Due to changes in #2300, it is now throwing a class cast exception which revealed the incorrect behavior

Exception:
```
    software.aws.toolkits.jetbrains.services.lambda.upload.CreateFunctionIntegrationTest > zip based lambda can be created FAILED
    java.lang.ClassCastException: class software.aws.toolkits.jetbrains.core.region.AwsRegionProvider cannot be cast to class software.aws.toolkits.jetbrains.core.region.MockRegionProvider (software.aws.toolkits.jetbrains.core.region.AwsRegionProvider and software.aws.toolkits.jetbrains.core.region.MockRegionProvider are in unnamed module of loader 'app')
    at software.aws.toolkits.jetbrains.core.region.MockRegionProvider$Companion.getInstance(MockRegionProvider.kt:64)
    at software.aws.toolkits.jetbrains.core.region.MockRegionProviderRule$lazyRegionProvider$1.invoke(MockRegionProvider.kt:70)
    at software.aws.toolkits.jetbrains.core.region.MockRegionProviderRule$lazyRegionProvider$1.invoke(MockRegionProvider.kt:68)
    at software.aws.toolkits.jetbrains.utils.rules.ClearableLazy.getValue(CodeInsightTestFixtureRule.kt:115)
    at software.aws.toolkits.jetbrains.core.region.MockRegionProviderRule.getRegionManager(MockRegionProvider.kt:74)
    at software.aws.toolkits.jetbrains.core.region.MockRegionProviderRule.addRegion(MockRegionProvider.kt:77)
    at software.aws.toolkits.jetbrains.services.lambda.upload.CreateFunctionIntegrationTest.setUp(CreateFunctionIntegrationTest.kt:88)
```

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by abrooksv** [comment]
Integration test failures are different test:

```
JavaDebugEndToEndTest

java.lang.AssertionError: Thread leaked: Thread[ForkJoinPool.commonPool-worker-1,4,main] (alive) TIMED_WAITING
--- its stacktrace:
 at java.base@11.0.8/jdk.internal.misc.Unsafe.park(Native Method)
 at java.base@11.0.8/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
 at java.base@11.0.8/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
 at java.base@11.0.8/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
---
stackTrace.length: 4
```

Have not triaged and fixed that one yet.

**Comment by abrooksv** [comment]
> Integration test failures are different test:
> 
> ```
> JavaDebugEndToEndTest
> 
> java.lang.AssertionError: Thread leaked: Thread[ForkJoinPool.commonPool-worker-1,4,main] (alive) TIMED_WAITING
> --- its stacktrace:
>  at java.base@11.0.8/jdk.internal.misc.Unsafe.park(Native Method)
>  at java.base@11.0.8/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
>  at java.base@11.0.8/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
>  at java.base@11.0.8/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> ---
> stackTrace.length: 4
> ```
> 
> Have not triaged and fixed that one yet.

https://github.com/aws/aws-toolkit-jetbrains/pull/2306 should fix this

**Review by kiiadi — APPROVED** [review]

**Pull request merged**
