### PR TITLE
Use standard gradle paths in UI tests

### PR DESCRIPTION
**Pull request by abrooksv**
The original issue (https://github.com/aws/aws-toolkit-jetbrains/pull/1368) has been fixed by the download plugin in https://github.com/michel-kraemer/gradle-download-task/releases/tag/4.0.4

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by hunterwerlla — APPROVED** [review]

**Comment by abrooksv** [comment]
There is some magical stuff in our UI test build that these changes break:

```
54 INFO  - [IDE Gradle]: Error occurred during initialization of VM
  18:39:09.854 ERROR - [IDE Gradle]: Error opening zip file or JAR manifest missing : ../../../../../../../../../../../codebuild/output/src508094253/src/github.com/aws/aws-toolkit-jetbrains/jetbrains-core/build/tmp/expandedArchives/org.jacoco.agent-0.8.5.jar_6a2df60c47de373ea127d14406367999/jacocoagent.jar
  18:39:09.854 INFO  - [IDE Gradle]: agent library failed to init: instrument
```

**Comment by abrooksv** [comment]
Caching seems to have caused the above issue, not sure if just corrupt cache due to moving paths around but will punt that part for now

**Pull request merged**
