### PR TITLE
Switch cloud debug integration tests to use the public ECR repository

### PR DESCRIPTION
**Pull request by hunterwerlla**
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kiiadi — APPROVED** [review]

**Review by abrooksv — APPROVED** [review]

**Comment by abrooksv** [comment]
approving since the tests passed, initial run failed due to our CFN rule is not re-entrant and this stack is shared for all 3 ide profiles

**Comment by hunterwerlla** [comment]
The pse cli cannot get from public registries other than dockerhub, closing for now :(

**Pull request closed without merging**
