### PR TITLE
fix(featureDev): file rejections for files outside of src/

### PR DESCRIPTION
**Pull request by dianaabv16**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Description
When the given path for a file starts with ./ it doesn't show the file actions and not triggering the file click. Now it uses the original file path check
It was fixed in the newest mynah release

Tested: yes, now files outside of src/ can be rejected
Screenshot 2024-06-19 at 16 45 10

## Checklist
- [x] My code follows the code style of this project
- [ ] I have added tests to cover my changes
- [x] A short description of the change has been added to the **[CHANGELOG](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md#contributing-via-pull-requests)** if the change is customer-facing in the IDE.
- [ ] I have added metrics for my changes (if required)
 
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kumsmrit — APPROVED** [review]

**Review by sarayev — APPROVED** [review]

**Review by rli — APPROVED** [review]

**Comment by dianaabv16** [comment]
@rli Could you merge this PR please? previous merged commits also fail with Windows Unit tests

**Comment by rli** [comment]
Replaced by https://github.com/aws/aws-toolkit-jetbrains/pull/4606

**Pull request closed without merging**
