### PR TITLE
Add Docs and GitHub link to explorer's gear menu

### LINKED ISSUE #875: Add links to GitHub and Docs in the Explorer's Gear Icon
In order to make it easier to go to GitHub / Docs, add links to the explorer's gear menu.

Doc link: https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/welcome.html

### PR DESCRIPTION
**Pull request by abrooksv**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Related Issue(s)
Fixes #875

## Screenshots (if appropriate)
Screen Shot 2019-04-04 at 1 35 39 PM

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by abrooksv** [comment]
Perma link will be ready in a few hours

**Comment by orozcoadrian** [comment]
Consider renaming the menu option to something more specific to the plugin, like "View AWS Toolkit in GitHub" or "View plugin source in GitHub", etc. to help distinguish it from the existing "Open on GitHub" option you get in the Version Control panel. Regardless, I think these links will be very helpful 👍

**Comment by abrooksv** [comment]
@orozcoadrian Thank you for the feedback, will discuss the concern with the team tomorrow.

**Comment by abrooksv** [comment]
@orozcoadrian We discussed it and we thought there was enough contextual information of having to right clicking on the AWS Explorer's status bar to indicate it was for the plugin only.

**Pull request merged**
