### PR TITLE
[CodeWhisperer] Update CodeWhisperer API model

### PR DESCRIPTION
**Pull request by Will-ShaoHua**
Update CWSPR API model

Corresponding VSC PR https://github.com/aws/aws-toolkit-vscode/pull/2795/files

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `gradlew check` succeeds
- [x] My code follows the code style of this project
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the **[CHANGELOG](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md#contributing-via-pull-requests)** if change is customer facing in the IDE.
 
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Will-ShaoHua** [comment]
Will open another PR for reformatting CWSPR service-2.json

**Comment by andrewyuq** [comment]
> Will open another follow-up PR for reformatting CWSPR service-2.json

what is reformatting service-2.json?

**Review by andrewyuq — APPROVED** [review]

**Comment by Will-ShaoHua** [comment]
> > Will open another follow-up PR for reformatting CWSPR service-2.json
> 
> what is reformatting service-2.json?

I think the format of this file is a little bit weird @andrewyuq

**Comment by andrewyuq** [comment]
> > > Will open another follow-up PR for reformatting CWSPR service-2.json
> > 
> > 
> > what is reformatting service-2.json?
> 
> I think the format of this file is a little bit weird @andrewyuq, i mean indentation/space/newline etc.

This file is auto generated, so no manual reformatting is needed

**Review by rli — APPROVED** [review]
will this ever be distributed through the regular AWS SDKs?

**Comment by Will-ShaoHua** [comment]
> will this ever be distributed through the regular AWS SDKs?

umm, I don't have the answer for this. @andrewyuq do you know this one? Thanks!

**Comment by andrewyuq** [comment]
> > will this ever be distributed through the regular AWS SDKs?
> 
> umm, I don't have the answer for this. @andrewyuq do you know this one? Thanks!

Not in the near future, I don't see there's an a plan at the moment.

**Pull request merged**
