### PR TITLE
Fix Lambda run configuration exception while setting handler architec…

### PR DESCRIPTION
**Pull request by rli**
…ture (#3056)
 
## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by manodnyab — APPROVED** [review]

**Comment by pradt2** [comment]
Hi, I tested this change, and unfortunately it does not solve https://github.com/aws/aws-toolkit-jetbrains/issues/3056 in my case.

To get the plugin to work, I had to change `LocalLambdaRunSettingsEditor.kt:67` to

```kotlin
configuration.architecture(LambdaArchitecture.fromValue(view.rawSettings.architecture.selected().toString()))
```

I suspect this change isn't a proper fix and the real issue lies elsewhere, but I hope this will point you in the right direction. I'm happy to do more testing for you if needed.

**Comment by rli** [comment]
@pradt2 I'm unable to reproduce the error with my current proposed change at `LocalLambdaRunSettingsEditor.kt:42`

The `validateSupportedArchitecture()` call should ensure that `view.rawSettings.architecture.selected()` later returns a valid `LambdaArchitecture` and therefore not require your proposal for L67. Though, I suppose there's no harm in adding a defensive check here. We can also afford to be a bit hacky here since the UI is due to be rewritten.

> To get the plugin to work

Are you referring to the ClassCastException, or debugging in general? Can you share the XML serialization of the run configuration that's giving you issues? It should be in `<workspace>/.idea/workspace.xml` and should look like the following:

```
    <configuration name="[Local] app.lambdaHandler" type="aws.lambda" factoryName="Local" nameIsGenerated="true">
      <option name="credentialProviderId" value="profile:default" />
      <option name="regionId" value="us-west-2" />
      <option name="debugHost" value="localhost" />
      <option name="architecture" value="x86_64" />
      <option name="environmentVariables">
        <map />
      </option>
      <option name="handler" value="app.lambdaHandler" />
      <option name="image" value="false" />
      <option name="logicalFunctionName" />
      <option name="memorySize" value="128" />
      <option name="pathMappings">
        <list />
      </option>
      <option name="platform" />
      <option name="runtime" value="python3.9" />
      <option name="templateFile" />
      <option name="timeout" value="300" />
      <option name="useTemplate" value="false" />
      <option name="input" value="&quot;&quot;" />
      <option name="inputIsFile" value="false" />
      <sam>
        <option name="additionalBuildArgs" value="" />
        <option name="additionalLocalArgs" value="" />
        <option name="buildInContainer" value="false" />
        <option name="dockerNetwork" value="" />
        <option name="skipImagePull" value="false" />
      </sam>
      <method v="2" />
    </configuration>
```

**Comment by pradt2** [comment]
Hey, I checked everything again, and it turns out I was building from the main branch of your fork... When I switched to the proper branch, the issue went away.

**Comment by rli** [comment]
@pradt2 Awesome, thanks for taking the time to check!

**Pull request merged**
