### PR TITLE
Change Solution name to default names when switching between templates

### PR DESCRIPTION
**Pull request by sdubov**
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Description
* Fix the issue with solution name persist a "HelloWorld" name when switching to AWS template. Remove flags to set solution and and project name by user that block using default solution names.

## Motivation and Context
Solution name should use a default template names unless name is set by user. The behavior should persists for each project type. It was broken after switching to AWS template.

## Related Issue(s)
None.

## Testing
Verified default template solution name persists if user does not change a name.
Verified value persists when changing by user.

## Screenshots (if appropriate)
None.

## Checklist
- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `gradlew check` succeeds
- [x] My code follows the code style of this project
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sdubov** [comment]
Sorry, please ignore for now. This PR need to be updated since we have no option to prevent Project name to be changed in that case. Working on it.

**Comment by abrooksv** [comment]
Is this for RIDER-33968?

**Comment by sdubov** [comment]
Yes.

**Comment by sdubov** [comment]
Fixed all related issues. Please review the PR. Solution name default value persists on switching between templates if user did not modify it. Project name remains unchanged.

**Pull request merged**
